services:
  docs:
    image: ticket_system_local_docs
    container_name: ticket_system_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ticket_system:/app/ticket_system:z
    ports:
      - '9000:9000'
    command: /start-docs
